D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamBLL.dll
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamBLL.pdb
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamCommon.dll
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamDAL.dll
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamModel.dll
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamCommon.pdb
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamDAL.pdb
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\bin\Debug\ExamModel.pdb
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\obj\Debug\ExamBLL.csprojResolveAssemblyReference.cache
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\obj\Debug\ExamBLL.dll
D:\工作\外包项目\20171030\Project\ExamProject\ExamBLL\obj\Debug\ExamBLL.pdb
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamBLL.dll
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamBLL.pdb
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamCommon.dll
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamDAL.dll
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamModel.dll
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamCommon.pdb
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamDAL.pdb
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\bin\Debug\ExamModel.pdb
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.csprojResolveAssemblyReference.cache
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.dll
C:\Users\DLH_PCM\Desktop\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.pdb
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamBLL.dll
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamBLL.pdb
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamCommon.dll
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamDAL.dll
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamModel.dll
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamCommon.pdb
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamDAL.pdb
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\bin\Debug\ExamModel.pdb
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.csprojResolveAssemblyReference.cache
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.dll
F:\WWW\ExamProject\20171119\ExamProject\ExamBLL\obj\Debug\ExamBLL.pdb
D:\C#项目\ExamBLL\bin\Debug\ExamBLL.dll
D:\C#项目\ExamBLL\bin\Debug\ExamBLL.pdb
D:\C#项目\ExamBLL\bin\Debug\ExamCommon.dll
D:\C#项目\ExamBLL\bin\Debug\ExamDAL.dll
D:\C#项目\ExamBLL\bin\Debug\ExamModel.dll
D:\C#项目\ExamBLL\bin\Debug\ExamCommon.pdb
D:\C#项目\ExamBLL\bin\Debug\ExamModel.pdb
D:\C#项目\ExamBLL\obj\Debug\ExamBLL.csprojAssemblyReference.cache
D:\C#项目\ExamBLL\obj\Debug\ExamBLL.csproj.CopyComplete
D:\C#项目\ExamBLL\obj\Debug\ExamBLL.dll
D:\C#项目\ExamBLL\obj\Debug\ExamBLL.pdb
